### ISSUE TITLE
Square Brackets Interference

### ISSUE THREAD

**Issue by marcguyer** [github-archive/task_list#51]
When using square brackets in the beginning of the content of a list item, the checking of boxes doesn't work as expected. Here's an example:
- [ ] This is a normal item
- [ ] [Try] one with brackets at the beginning
- [x] Try one [with] brackets in the middle
- [ ] No brackets again

For a good time, try clicking the second task.

**Comment by marcguyer** [comment]
Here's another thought:

- [x] [What about a link](http://google.com) at the beginning?

**Comment by marcguyer** [comment]
I see now that you can optionally (perhaps unnecessarily?) use a space between the brackets in a reference-style link:

http://daringfireball.net/projects/markdown/syntax#link

That's annoying but perhaps still should be considered a bug?

**Comment by mtodd** [comment]
@marcguyer thanks for reporting this issue! The rendering looks fine, but the update behavior does appear to be affected by this issue.

Markdown gives us the `\` to escape the brackets to prevent it from being rendered as a link, which will fix the broken behavior here, too. For instance:

``` markdown
- [ ] [try] breaks things, but
- [ ] \[try] works
```

- [ ] [try] breaks things, but
- [ ] \[try] works

Unfortunately, you need to put the `\` in front of the brackets on all of the lines that you want to use square brackets on, otherwise it'll be broken.

I'll try to dig in and figure out how to prevent the issue.

**Comment by deckar01** [comment]
This issue was moved to deckar01/task_list#4
